apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1 # For 2 sub url use: /$2
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: flaskapp.com
      http:
          paths:
            - path: /?(.*) # For sub url use: /appui(/|$)(.*)
              pathType: Prefix
              backend:
                service:
                  name: frontend-service
                  port:
                    number: 3001
            - path: /api/?(.*) # For sub url and their sub urls use: /back(/|$)(.*)
              pathType: Prefix
              backend:
                service:
                  name: flask-service
                  port:
                    number: 5001
